[package]
name = "chips"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive", "string"] }
serde_derive = "1.0"
serde = "1.0"
serde_json = "1.0.134"
strum = { version = "0.26.3", features = ["derive"] }
once_cell = "1.20.2"
